from pandas.core.arrays.categorical import Categorical
from typing import Any

def recode_for_groupby(c: Categorical, sort: bool, observed: bool) -> Any: ...
def recode_from_groupby(c: Categorical, sort: bool, ci: Any) -> Any: ...
