import numpy as np
from pandas._typing import FrameOrSeries as FrameOrSeries
from pandas.core.groupby import ops
from pandas.core.indexes.api import Index
from typing import Any, Dict, Hashable, List, Optional, Tuple

class Grouper:
    def __new__(cls, *args: Any, **kwargs: Any): ...
    key: Any = ...
    level: Any = ...
    freq: Any = ...
    axis: Any = ...
    sort: Any = ...
    grouper: Any = ...
    obj: Any = ...
    indexer: Any = ...
    binner: Any = ...
    def __init__(self, key: Optional[Any] = ..., level: Optional[Any] = ..., freq: Optional[Any] = ..., axis: int = ..., sort: bool = ...) -> None: ...
    @property
    def ax(self): ...
    @property
    def groups(self): ...

class Grouping:
    name: Any = ...
    level: Any = ...
    grouper: Any = ...
    all_grouper: Any = ...
    index: Any = ...
    sort: Any = ...
    obj: Any = ...
    observed: Any = ...
    in_axis: Any = ...
    def __init__(self, index: Index, grouper: Any=..., obj: Optional[FrameOrSeries]=..., name: Any=..., level: Any=..., sort: bool=..., observed: bool=..., in_axis: bool=...) -> None: ...
    def __iter__(self) -> Any: ...
    @property
    def ngroups(self) -> int: ...
    def indices(self): ...
    @property
    def codes(self) -> np.ndarray: ...
    def result_index(self) -> Index: ...
    @property
    def group_index(self) -> Index: ...
    def groups(self) -> Dict[Hashable, np.ndarray]: ...

def get_grouper(obj: FrameOrSeries, key: Any=..., axis: int=..., level: Any=..., sort: bool=..., observed: bool=..., mutated: bool=..., validate: bool=...) -> Tuple[ops.BaseGrouper, List[Hashable], FrameOrSeries]: ...
