import abc
from typing import Any, Optional

def read_excel(io: Any, sheet_name: int = ..., header: int = ..., names: Optional[Any] = ..., index_col: Optional[Any] = ..., usecols: Optional[Any] = ..., squeeze: bool = ..., dtype: Optional[Any] = ..., engine: Optional[Any] = ..., converters: Optional[Any] = ..., true_values: Optional[Any] = ..., false_values: Optional[Any] = ..., skiprows: Optional[Any] = ..., nrows: Optional[Any] = ..., na_values: Optional[Any] = ..., keep_default_na: bool = ..., verbose: bool = ..., parse_dates: bool = ..., date_parser: Optional[Any] = ..., thousands: Optional[Any] = ..., comment: Optional[Any] = ..., skipfooter: int = ..., convert_float: bool = ..., mangle_dupe_cols: bool = ..., **kwds: Any): ...

class _BaseExcelReader(metaclass=abc.ABCMeta):
    book: Any = ...
    def __init__(self, filepath_or_buffer: Any) -> None: ...
    @abc.abstractmethod
    def load_workbook(self, filepath_or_buffer: Any) -> Any: ...
    def close(self) -> None: ...
    @property
    @abc.abstractmethod
    def sheet_names(self) -> Any: ...
    @abc.abstractmethod
    def get_sheet_by_name(self, name: Any) -> Any: ...
    @abc.abstractmethod
    def get_sheet_by_index(self, index: Any) -> Any: ...
    @abc.abstractmethod
    def get_sheet_data(self, sheet: Any, convert_float: Any) -> Any: ...
    def parse(self, sheet_name: int = ..., header: int = ..., names: Optional[Any] = ..., index_col: Optional[Any] = ..., usecols: Optional[Any] = ..., squeeze: bool = ..., dtype: Optional[Any] = ..., true_values: Optional[Any] = ..., false_values: Optional[Any] = ..., skiprows: Optional[Any] = ..., nrows: Optional[Any] = ..., na_values: Optional[Any] = ..., verbose: bool = ..., parse_dates: bool = ..., date_parser: Optional[Any] = ..., thousands: Optional[Any] = ..., comment: Optional[Any] = ..., skipfooter: int = ..., convert_float: bool = ..., mangle_dupe_cols: bool = ..., **kwds: Any): ...

class ExcelWriter(metaclass=abc.ABCMeta):
    def __new__(cls, path: Any, engine: Optional[Any] = ..., **kwargs: Any): ...
    book: Any = ...
    curr_sheet: Any = ...
    path: Any = ...
    @property
    @abc.abstractmethod
    def supported_extensions(self) -> Any: ...
    @property
    @abc.abstractmethod
    def engine(self) -> Any: ...
    @abc.abstractmethod
    def write_cells(self, cells: Any, sheet_name: Optional[Any] = ..., startrow: int = ..., startcol: int = ..., freeze_panes: Optional[Any] = ...) -> Any: ...
    @abc.abstractmethod
    def save(self) -> Any: ...
    sheets: Any = ...
    cur_sheet: Any = ...
    date_format: str = ...
    datetime_format: str = ...
    mode: Any = ...
    def __init__(self, path: Any, engine: Optional[Any] = ..., date_format: Optional[Any] = ..., datetime_format: Optional[Any] = ..., mode: str = ..., **engine_kwargs: Any) -> None: ...
    def __fspath__(self): ...
    @classmethod
    def check_extension(cls, ext: Any): ...
    def __enter__(self): ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...
    def close(self): ...

class ExcelFile:
    engine: Any = ...
    io: Any = ...
    def __init__(self, io: Any, engine: Optional[Any] = ...) -> None: ...
    def __fspath__(self): ...
    def parse(self, sheet_name: int = ..., header: int = ..., names: Optional[Any] = ..., index_col: Optional[Any] = ..., usecols: Optional[Any] = ..., squeeze: bool = ..., converters: Optional[Any] = ..., true_values: Optional[Any] = ..., false_values: Optional[Any] = ..., skiprows: Optional[Any] = ..., nrows: Optional[Any] = ..., na_values: Optional[Any] = ..., parse_dates: bool = ..., date_parser: Optional[Any] = ..., thousands: Optional[Any] = ..., comment: Optional[Any] = ..., skipfooter: int = ..., convert_float: bool = ..., mangle_dupe_cols: bool = ..., **kwds: Any): ...
    @property
    def book(self): ...
    @property
    def sheet_names(self): ...
    def close(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...
    def __del__(self) -> None: ...
