import numpy as np
from pandas.core.dtypes.generic import ABCExtensionArray
from typing import Any, Optional, Union

def comp_method_OBJECT_ARRAY(op: Any, x: Any, y: Any): ...
def masked_arith_op(x: Any, y: Any, op: Any): ...
def define_na_arithmetic_op(op: Any, str_rep: str) -> Any: ...
def na_arithmetic_op(left: Any, right: Any, op: Any, str_rep: str) -> Any: ...
def arithmetic_op(left: Union[np.ndarray, ABCExtensionArray], right: Any, op: Any, str_rep: str) -> Any: ...
def comparison_op(left: Union[np.ndarray, ABCExtensionArray], right: Any, op: Any) -> Union[np.ndarray, ABCExtensionArray]: ...
def na_logical_op(x: np.ndarray, y: Any, op: Any) -> Any: ...
def logical_op(left: Union[np.ndarray, ABCExtensionArray], right: Any, op: Any) -> Union[np.ndarray, ABCExtensionArray]: ...
def get_array_op(op: Any, str_rep: Optional[str]=...) -> Any: ...
