from typing import Any

def fill_zeros(result: Any, x: Any, y: Any): ...
def mask_zero_div_zero(x: Any, y: Any, result: Any): ...
def dispatch_fill_zeros(op: Any, left: Any, right: Any, result: Any): ...
