from pandas._typing import FilePathOrBuffer as FilePathOrBuffer
from typing import Any, Optional

def to_pickle(obj: Any, filepath_or_buffer: FilePathOrBuffer, compression: Optional[str]=..., protocol: int=...) -> Any: ...
def read_pickle(filepath_or_buffer: FilePathOrBuffer, compression: Optional[str]=...) -> Any: ...
