runner:
  mypy:
    cmd: mypy --strict --show-column-numbers benchbuild
    errorformat:
      - "%f:%l:%c: %m"
    level: error

  ruff:
    cmd: ruff check --output-format=github benchbuild
    errorformat:
      - "%f:%l:%c: %m"
    level: warning
