from .. import events as events
from typing import Any

class ConventionDict:
    const: Any = ...
    table: Any = ...
    convention: Any = ...
    def __init__(self, const: Any, table: Any, convention: Any) -> None: ...
    def __getitem__(self, key: Any): ...
