from typing import Any, Optional

class _fake_lock:
    def acquire(self, val: Any): ...
    def release(self) -> None: ...

def posix_daemonize(command: Any, cwd: Any, stdout: Optional[Any] = ..., stderr: Optional[Any] = ..., append: bool = ...): ...
def win32_daemonize(command: Any, cwd: Any, stdout: Optional[Any] = ..., stderr: Optional[Any] = ..., append: bool = ...): ...
