from typing import Any

def getpriority(*args, **kwargs) -> Any: ...
def net_if_addrs(*args, **kwargs) -> Any: ...
def net_if_flags(*args, **kwargs) -> Any: ...
def net_if_mtu(*args, **kwargs) -> Any: ...
def setpriority(*args, **kwargs) -> Any: ...
