import numpy.ma as np
from typing import Any, Optional

def arrays_to_mgr(arrays: Any, arr_names: Any, index: Any, columns: Any, dtype: Optional[Any] = ...): ...
def masked_rec_array_to_mgr(data: Any, index: Any, columns: Any, dtype: Any, copy: Any): ...
def init_ndarray(values: Any, index: Any, columns: Any, dtype: Optional[Any] = ..., copy: bool = ...): ...
def init_dict(data: Any, index: Any, columns: Any, dtype: Optional[Any] = ...): ...
def prep_ndarray(values: Any, copy: Any=...) -> np.ndarray: ...
def extract_index(data: Any): ...
def reorder_arrays(arrays: Any, arr_columns: Any, columns: Any): ...
def get_names_from_index(data: Any): ...
def to_arrays(data: Any, columns: Any, coerce_float: bool = ..., dtype: Optional[Any] = ...): ...
def sanitize_index(data: Any, index: Any, copy: bool = ...): ...
