from migrate.changeset import ansisql
from typing import Any

FBSchemaGenerator: Any

class FBColumnGenerator(FBSchemaGenerator, ansisql.ANSIColumnGenerator): ...

class FBColumnDropper(ansisql.ANSIColumnDropper):
    def visit_column(self, column: Any) -> None: ...

class FBSchemaChanger(ansisql.ANSISchemaChanger):
    def visit_table(self, table: Any) -> None: ...

class FBConstraintGenerator(ansisql.ANSIConstraintGenerator): ...

class FBConstraintDropper(ansisql.ANSIConstraintDropper):
    def cascade_constraint(self, constraint: Any) -> None: ...

class FBDialect(ansisql.ANSIDialect):
    columngenerator: Any = ...
    columndropper: Any = ...
    schemachanger: Any = ...
    constraintgenerator: Any = ...
    constraintdropper: Any = ...
