from migrate.changeset import ansisql, util as util
from typing import Any

MySQLSchemaGenerator: Any

class MySQLColumnGenerator(MySQLSchemaGenerator, ansisql.ANSIColumnGenerator): ...
class MySQLColumnDropper(ansisql.ANSIColumnDropper): ...

class MySQLSchemaChanger(MySQLSchemaGenerator, ansisql.ANSISchemaChanger):
    def visit_column(self, delta: Any) -> None: ...
    def visit_index(self, param: Any) -> None: ...

class MySQLConstraintGenerator(ansisql.ANSIConstraintGenerator): ...

class MySQLConstraintDropper(MySQLSchemaGenerator, ansisql.ANSIConstraintDropper):
    def visit_migrate_check_constraint(self, *p: Any, **k: Any) -> None: ...

class MySQLDialect(ansisql.ANSIDialect):
    columngenerator: Any = ...
    columndropper: Any = ...
    schemachanger: Any = ...
    constraintgenerator: Any = ...
    constraintdropper: Any = ...
