from migrate.changeset import ansisql
from typing import Any

OracleSchemaGenerator: Any

class OracleColumnGenerator(OracleSchemaGenerator, ansisql.ANSIColumnGenerator): ...
class OracleColumnDropper(ansisql.ANSIColumnDropper): ...

class OracleSchemaChanger(OracleSchemaGenerator, ansisql.ANSISchemaChanger):
    def get_column_specification(self, column: Any, **kwargs: Any): ...
    def visit_column(self, delta: Any) -> None: ...

class OracleConstraintCommon:
    def get_constraint_name(self, cons: Any): ...

class OracleConstraintGenerator(OracleConstraintCommon, ansisql.ANSIConstraintGenerator): ...
class OracleConstraintDropper(OracleConstraintCommon, ansisql.ANSIConstraintDropper): ...

class OracleDialect(ansisql.ANSIDialect):
    columngenerator: Any = ...
    columndropper: Any = ...
    schemachanger: Any = ...
    constraintgenerator: Any = ...
    constraintdropper: Any = ...
