from migrate.changeset import ansisql
from typing import Any

PGSchemaGenerator: Any

class PGColumnGenerator(PGSchemaGenerator, ansisql.ANSIColumnGenerator): ...
class PGColumnDropper(ansisql.ANSIColumnDropper): ...
class PGSchemaChanger(ansisql.ANSISchemaChanger): ...
class PGConstraintGenerator(ansisql.ANSIConstraintGenerator): ...
class PGConstraintDropper(ansisql.ANSIConstraintDropper): ...

class PGDialect(ansisql.ANSIDialect):
    columngenerator: Any = ...
    columndropper: Any = ...
    schemachanger: Any = ...
    constraintgenerator: Any = ...
    constraintdropper: Any = ...
