from typing import Any, Optional

DIALECTS: Any

def get_engine_visitor(engine: Any, name: Any): ...
def get_dialect_visitor(sa_dialect: Any, name: Any): ...
def run_single_visitor(engine: Any, visitorcallable: Any, element: Any, connection: Optional[Any] = ..., **kwargs: Any) -> None: ...
