import numpy as np
from .masked import BaseMaskedArray
from pandas._typing import Scalar as Scalar
from pandas.core.dtypes.base import ExtensionDtype
from typing import Any, Type

class BooleanDtype(ExtensionDtype):
    name: str = ...
    @property
    def na_value(self) -> Scalar: ...
    @property
    def type(self) -> Type: ...
    @property
    def kind(self) -> str: ...
    @classmethod
    def construct_array_type(cls: Any) -> Type[BooleanArray]: ...
    def __from_arrow__(self, array: Any): ...

def coerce_to_array(values: Any, mask: Any=..., copy: bool=...) -> Any: ...

class BooleanArray(BaseMaskedArray):
    def __init__(self, values: np.ndarray, mask: np.ndarray, copy: bool=...) -> None: ...
    @property
    def dtype(self): ...
    def __array_ufunc__(self, ufunc: Any, method: Any, *inputs: Any, **kwargs: Any): ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def astype(self, dtype: Any, copy: bool = ...): ...
    def any(self, skipna: bool=..., **kwargs: Any) -> Any: ...
    def all(self, skipna: bool=..., **kwargs: Any) -> Any: ...
