import numpy as np
from pandas._typing import Scalar as Scalar
from pandas.core.arrays import ExtensionArray, ExtensionOpsMixin
from typing import Any, Optional

class BaseMaskedArray(ExtensionArray, ExtensionOpsMixin):
    def __getitem__(self, item: Any): ...
    def __iter__(self) -> Any: ...
    def __len__(self) -> int: ...
    def __invert__(self): ...
    def to_numpy(self, dtype: Any=..., copy: Any=..., na_value: Scalar=...) -> Any: ...
    __array_priority__: int = ...
    def __array__(self, dtype: Any=...) -> np.ndarray: ...
    def __arrow_array__(self, type: Optional[Any] = ...): ...
    def isna(self): ...
    @property
    def nbytes(self): ...
    def take(self, indexer: Any, allow_fill: bool = ..., fill_value: Optional[Any] = ...): ...
    def copy(self): ...
    def value_counts(self, dropna: bool = ...): ...
