from pandas.core.arrays import PandasArray
from pandas.core.dtypes.base import ExtensionDtype
from typing import Any, Optional, Type

class StringDtype(ExtensionDtype):
    name: str = ...
    na_value: Any = ...
    @property
    def type(self) -> Type: ...
    @classmethod
    def construct_array_type(cls: Any) -> Type[StringArray]: ...
    def __from_arrow__(self, array: Any): ...

class StringArray(PandasArray):
    def __init__(self, values: Any, copy: bool = ...) -> None: ...
    def __arrow_array__(self, type: Optional[Any] = ...): ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def fillna(self, value: Optional[Any] = ..., method: Optional[Any] = ..., limit: Optional[Any] = ...): ...
    def astype(self, dtype: Any, copy: bool = ...): ...
    def value_counts(self, dropna: bool = ...): ...
