from typing import Any

isposinf_scalar: Any
isneginf_scalar: Any

def isna(obj: Any): ...
isnull = isna

def notna(obj: Any): ...
notnull = notna

def array_equivalent(left: Any, right: Any, strict_nan: bool=...) -> bool: ...
def na_value_for_dtype(dtype: Any, compat: bool=...) -> Any: ...
def remove_na_arraylike(arr: Any): ...
def is_valid_nat_for_dtype(obj: Any, dtype: Any) -> bool: ...
