# Extend the DIRS variable if you want make to setup new
# folders for you. This will create the missing directories
# and link the latex/Makefile.
#
DIRS = adi fdtd-2d fdtd-apml jacobi-1d-imper jacobi-2d-imper seidel-2d
LEVEL = ../..

include $(LEVEL)/Makefile.common
