from migrate.exceptions import *
from sqlalchemy import schema
from typing import Any

class ConstraintChangeset:
    def create(self, *a: Any, **kw: Any) -> None: ...
    cascade: Any = ...
    def drop(self, *a: Any, **kw: Any): ...

class PrimaryKeyConstraint(ConstraintChangeset, schema.PrimaryKeyConstraint):
    __migrate_visit_name__: str = ...
    def __init__(self, *cols: Any, **kwargs: Any) -> None: ...
    def autoname(self): ...

class ForeignKeyConstraint(ConstraintChangeset, schema.ForeignKeyConstraint):
    __migrate_visit_name__: str = ...
    def __init__(self, columns: Any, refcolumns: Any, *args: Any, **kwargs: Any) -> None: ...
    @property
    def referenced(self): ...
    @property
    def reftable(self): ...
    def autoname(self): ...

class CheckConstraint(ConstraintChangeset, schema.CheckConstraint):
    __migrate_visit_name__: str = ...
    colnames: Any = ...
    def __init__(self, sqltext: Any, *args: Any, **kwargs: Any) -> None: ...
    def autoname(self): ...

class UniqueConstraint(ConstraintChangeset, schema.UniqueConstraint):
    __migrate_visit_name__: str = ...
    def __init__(self, *cols: Any, **kwargs: Any) -> None: ...
    def autoname(self): ...
