from pandas.core.accessor import DirNamesMixin
from pandas.core.arrays import ExtensionArray
from typing import Any, Optional

class PandasObject(DirNamesMixin):
    def __sizeof__(self): ...

class NoNewAttributesMixin:
    def __setattr__(self, key: Any, value: Any) -> None: ...

class GroupByError(Exception): ...
class DataError(GroupByError): ...
class SpecificationError(GroupByError): ...

class SelectionMixin:
    def ndim(self) -> int: ...
    def __getitem__(self, key: Any): ...
    def aggregate(self, func: Any, *args: Any, **kwargs: Any) -> None: ...
    agg: Any = ...

class ShallowMixin: ...

class IndexOpsMixin:
    __array_priority__: int = ...
    def transpose(self, *args: Any, **kwargs: Any): ...
    T: Any = ...
    @property
    def shape(self): ...
    @property
    def ndim(self) -> int: ...
    def item(self): ...
    @property
    def nbytes(self): ...
    @property
    def size(self): ...
    @property
    def array(self) -> ExtensionArray: ...
    def to_numpy(self, dtype: Optional[Any] = ..., copy: bool = ..., na_value: Any = ..., **kwargs: Any): ...
    @property
    def empty(self): ...
    def max(self, axis: Optional[Any] = ..., skipna: bool = ..., *args: Any, **kwargs: Any): ...
    def argmax(self, axis: Optional[Any] = ..., skipna: bool = ..., *args: Any, **kwargs: Any): ...
    def min(self, axis: Optional[Any] = ..., skipna: bool = ..., *args: Any, **kwargs: Any): ...
    def argmin(self, axis: Optional[Any] = ..., skipna: bool = ..., *args: Any, **kwargs: Any): ...
    def tolist(self): ...
    to_list: Any = ...
    def __iter__(self) -> Any: ...
    def hasnans(self): ...
    def value_counts(self, normalize: bool = ..., sort: bool = ..., ascending: bool = ..., bins: Optional[Any] = ..., dropna: bool = ...): ...
    def unique(self): ...
    def nunique(self, dropna: bool = ...): ...
    @property
    def is_unique(self): ...
    @property
    def is_monotonic(self): ...
    is_monotonic_increasing: Any = ...
    @property
    def is_monotonic_decreasing(self) -> bool: ...
    def memory_usage(self, deep: bool = ...): ...
    def factorize(self, sort: bool = ..., na_sentinel: int = ...): ...
    def searchsorted(self, value: Any, side: str = ..., sorter: Optional[Any] = ...): ...
    def drop_duplicates(self, keep: str = ..., inplace: bool = ...): ...
    def duplicated(self, keep: str = ...): ...
