from typing import Any

log: Any

def usage() -> None: ...
def delete_file(filepath: Any) -> None: ...
def move_file(src: Any, tgt: Any) -> None: ...
def delete_directory(dirpath: Any) -> None: ...
def migrate_repository(repos: Any) -> None: ...
def main() -> None: ...
