from migrate.versioning.config import *
from migrate.versioning.util import KeyedInstance
from typing import Any

log: Any

class Pathed(KeyedInstance):
    parent: Any = ...
    path: Any = ...
    def __init__(self, path: Any) -> None: ...
    @classmethod
    def require_notfound(cls, path: Any) -> None: ...
    @classmethod
    def require_found(cls, path: Any) -> None: ...
