from typing import Any, Optional

log: Any

def getDiffOfModelAgainstDatabase(metadata: Any, engine: Any, excludeTables: Optional[Any] = ...): ...
def getDiffOfModelAgainstModel(metadataA: Any, metadataB: Any, excludeTables: Optional[Any] = ...): ...

class ColDiff:
    diff: bool = ...
    col_A: Any = ...
    col_B: Any = ...
    type_A: Any = ...
    type_B: Any = ...
    affinity_A: Any = ...
    affinity_B: Any = ...
    def __init__(self, col_A: Any, col_B: Any) -> None: ...
    def __nonzero__(self): ...
    __bool__: Any = ...

class TableDiff:
    def __nonzero__(self): ...
    __bool__: Any = ...

class SchemaDiff:
    label_width: Any = ...
    tables_missing_from_A: Any = ...
    tables_missing_from_B: Any = ...
    tables_different: Any = ...
    def __init__(self, metadataA: Any, metadataB: Any, labelA: str = ..., labelB: str = ..., excludeTables: Optional[Any] = ...) -> None: ...
    def __len__(self): ...
