from migrate.versioning.config import *
from migrate.versioning import pathed
from typing import Any, Optional

class Collection(pathed.Pathed):
    def get_path(self, file: Any): ...

class RepositoryCollection(Collection): ...
class ScriptCollection(Collection): ...
class ManageCollection(Collection): ...
class SQLScriptCollection(Collection): ...

class Template(pathed.Pathed):
    pkg: str = ...
    def __new__(cls, path: Optional[Any] = ...): ...
    repository: Any = ...
    script: Any = ...
    manage: Any = ...
    sql_script: Any = ...
    def __init__(self, path: Optional[Any] = ...) -> None: ...
    def get_repository(self, *a: Any, **kw: Any): ...
    def get_script(self, *a: Any, **kw: Any): ...
    def get_sql_script(self, *a: Any, **kw: Any): ...
    def get_manage(self, *a: Any, **kw: Any): ...
