name: "Setup BenchBuild Runner Environment"
description: "Install APT system depedcies"
inputs:
  python-version:
    description: "The python version to use"
    type: string
    required: false
    default: "3.14"
runs:
  using: "composite"
  steps:
    - name: Cache APT Packages
      uses: actions/cache@v6
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-${{ hashFiles('**/packages.list') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Install APT Dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y \
          podman \
          clang \
          time \
          unionfs-fuse \
          libfuse-dev \
          libgit2-dev

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install the project
      shell: bash
      run: |
        uv sync --locked --all-extras --dev
