from pandas.core.accessor import PandasDelegate
from pandas.core.base import NoNewAttributesMixin, PandasObject
from typing import Any

class Properties(PandasDelegate, PandasObject, NoNewAttributesMixin):
    orig: Any = ...
    name: Any = ...
    def __init__(self, data: Any, orig: Any) -> None: ...

class DatetimeProperties(Properties):
    def to_pydatetime(self): ...
    @property
    def freq(self): ...

class TimedeltaProperties(Properties):
    def to_pytimedelta(self): ...
    @property
    def components(self): ...
    @property
    def freq(self): ...

class PeriodProperties(Properties): ...

class CombinedDatetimelikeProperties(DatetimeProperties, TimedeltaProperties, PeriodProperties):
    def __new__(cls, data: Any): ...
