import numpy as np
from datetime import tzinfo
from pandas.core.indexes.datetimelike import DatetimeTimedeltaMixin, DatetimelikeDelegateMixin
from typing import Any, Optional

class DatetimeDelegateMixin(DatetimelikeDelegateMixin): ...

class DatetimeIndex(DatetimeTimedeltaMixin, DatetimeDelegateMixin):
    tz: Optional[tzinfo]
    def __new__(cls, data: Optional[Any] = ..., freq: Optional[Any] = ..., tz: Optional[Any] = ..., normalize: bool = ..., closed: Optional[Any] = ..., ambiguous: str = ..., dayfirst: bool = ..., yearfirst: bool = ..., dtype: Optional[Any] = ..., copy: bool = ..., name: Optional[Any] = ...): ...
    def __array__(self, dtype: Any=...) -> np.ndarray: ...
    def __reduce__(self): ...
    def union_many(self, others: Any): ...
    def to_series(self, keep_tz: Any = ..., index: Optional[Any] = ..., name: Optional[Any] = ...): ...
    def snap(self, freq: str = ...): ...
    def get_value(self, series: Any, key: Any): ...
    def get_value_maybe_box(self, series: Any, key: Any): ...
    def get_loc(self, key: Any, method: Optional[Any] = ..., tolerance: Optional[Any] = ...): ...
    def slice_indexer(self, start: Optional[Any] = ..., end: Optional[Any] = ..., step: Optional[Any] = ..., kind: Optional[Any] = ...): ...
    def searchsorted(self, value: Any, side: str = ..., sorter: Optional[Any] = ...): ...
    def is_type_compatible(self, typ: Any) -> bool: ...
    @property
    def inferred_type(self) -> str: ...
    def insert(self, loc: Any, item: Any): ...
    def indexer_at_time(self, time: Any, asof: bool = ...): ...
    def indexer_between_time(self, start_time: Any, end_time: Any, include_start: bool = ..., include_end: bool = ...): ...

def date_range(start: Any=..., end: Any=..., periods: Any=..., freq: Any=..., tz: Any=..., normalize: Any=..., name: Any=..., closed: Any=..., **kwargs: Any) -> DatetimeIndex: ...
def bdate_range(start: Any=..., end: Any=..., periods: Any=..., freq: Any=..., tz: Any=..., normalize: Any=..., name: Any=..., weekmask: Any=..., holidays: Any=..., closed: Any=..., **kwargs: Any) -> DatetimeIndex: ...
