from pandas.core.groupby.base import GroupByMixin
from typing import Any, Callable, Optional

class WindowGroupByMixin(GroupByMixin):
    def __init__(self, obj: Any, *args: Any, **kwargs: Any) -> None: ...
    count: Any = ...
    corr: Any = ...
    cov: Any = ...

def calculate_center_offset(window: Any): ...
def calculate_min_periods(window: int, min_periods: Optional[int], num_values: int, required_min_periods: int, floor: int) -> int: ...
def zsqrt(x: Any): ...
def prep_binary(arg1: Any, arg2: Any): ...
def get_weighted_roll_func(cfunc: Callable) -> Callable: ...
