from pandas import DataFrame
from pandas._typing import FrameOrSeriesUnion as FrameOrSeriesUnion
from typing import Any, Hashable, Iterable, Mapping, Optional, Union

def concat(objs: Union[Iterable[DataFrame], Mapping[Optional[Hashable], DataFrame]], axis: Any=..., join: str=..., ignore_index: bool=..., keys: Any=..., levels: Any=..., names: Any=..., verify_integrity: bool=..., sort: bool=..., copy: bool=...) -> DataFrame: ...

class _Concatenator:
    intersect: bool = ...
    objs: Any = ...
    axis: Any = ...
    keys: Any = ...
    names: Any = ...
    levels: Any = ...
    sort: Any = ...
    ignore_index: Any = ...
    verify_integrity: Any = ...
    copy: Any = ...
    new_axes: Any = ...
    def __init__(self, objs: Any, axis: Any=..., join: str=..., keys: Any=..., levels: Any=..., names: Any=..., ignore_index: bool=..., verify_integrity: bool=..., copy: bool=..., sort: Any=...) -> None: ...
    def get_result(self): ...
