from pandas.core.frame import DataFrame
from typing import Any

def melt(frame: DataFrame, id_vars: Any=..., value_vars: Any=..., var_name: Any=..., value_name: Any=..., col_level: Any=...) -> DataFrame: ...
def lreshape(data: DataFrame, groups: Any, dropna: bool=..., label: Any=...) -> DataFrame: ...
def wide_to_long(df: DataFrame, stubnames: Any, i: Any, j: Any, sep: str=..., suffix: str=...) -> DataFrame: ...
