from pandas import DataFrame, Series
from pandas._typing import FrameOrSeries as FrameOrSeries
from pandas.core import groupby as groupby
from typing import Any, Union

def merge(left: Any, right: Any, how: str=..., on: Any=..., left_on: Any=..., right_on: Any=..., left_index: bool=..., right_index: bool=..., sort: bool=..., suffixes: Any=..., copy: bool=..., indicator: bool=..., validate: Any=...) -> DataFrame: ...
def merge_ordered(left: Any, right: Any, on: Any=..., left_on: Any=..., right_on: Any=..., left_by: Any=..., right_by: Any=..., fill_method: Any=..., suffixes: Any=..., how: str=...) -> DataFrame: ...
def merge_asof(left: Any, right: Any, on: Any=..., left_on: Any=..., right_on: Any=..., left_index: bool=..., right_index: bool=..., by: Any=..., left_by: Any=..., right_by: Any=..., suffixes: Any=..., tolerance: Any=..., allow_exact_matches: bool=..., direction: str=...) -> DataFrame: ...

class _MergeOperation:
    left: Any = ...
    right: Any = ...
    how: Any = ...
    axis: Any = ...
    on: Any = ...
    left_on: Any = ...
    right_on: Any = ...
    copy: Any = ...
    suffixes: Any = ...
    sort: Any = ...
    left_index: Any = ...
    right_index: Any = ...
    indicator: Any = ...
    indicator_name: Any
    def __init__(self, left: Union[Series, DataFrame], right: Union[Series, DataFrame], how: str=..., on: Any=..., left_on: Any=..., right_on: Any=..., axis: Any=..., left_index: bool=..., right_index: bool=..., sort: bool=..., suffixes: Any=..., copy: bool=..., indicator: bool=..., validate: Any=...) -> None: ...
    def get_result(self): ...

class _OrderedMerge(_MergeOperation):
    fill_method: Any = ...
    def __init__(self, left: Any, right: Any, on: Any=..., left_on: Any=..., right_on: Any=..., left_index: bool=..., right_index: bool=..., axis: Any=..., suffixes: Any=..., copy: bool=..., fill_method: Any=..., how: str=...) -> None: ...
    def get_result(self): ...

class _AsOfMerge(_OrderedMerge):
    by: Any = ...
    left_by: Any = ...
    right_by: Any = ...
    tolerance: Any = ...
    allow_exact_matches: Any = ...
    direction: Any = ...
    def __init__(self, left: Any, right: Any, on: Any=..., left_on: Any=..., right_on: Any=..., left_index: bool=..., right_index: bool=..., by: Any=..., left_by: Any=..., right_by: Any=..., axis: Any=..., suffixes: Any=..., copy: bool=..., fill_method: Any=..., how: str=..., tolerance: Any=..., allow_exact_matches: bool=..., direction: str=...) -> None: ...
