from pandas import DataFrame
from typing import Any

def pivot_table(data: Any, values: Any=..., index: Any=..., columns: Any=..., aggfunc: Any=..., fill_value: Any=..., margins: Any=..., dropna: Any=..., margins_name: Any=..., observed: Any=...) -> DataFrame: ...
def pivot(data: DataFrame, index: Any=..., columns: Any=..., values: Any=...) -> DataFrame: ...
def crosstab(index: Any, columns: Any, values: Any=..., rownames: Any=..., colnames: Any=..., aggfunc: Any=..., margins: Any=..., margins_name: str=..., dropna: bool=..., normalize: Any=...) -> DataFrame: ...
