from typing import Any

def separate_glyphs(gdata: Any, height: Any): ...
def get_all_fonts(): ...
def add_font(name: Any, cls: Any) -> None: ...

class Font:
    char: Any = ...
    canvas: Any = ...
    utf8_required: bool = ...
    def __init__(self) -> None: ...
    def add_glyphs(self, gdata: Any) -> None: ...
    def characters(self): ...
    def char_width(self, c: Any): ...
    def char_data(self, c: Any): ...
    def render(self, c: Any): ...

class Thin3x3Font(Font):
    height: int = ...
    data: Any = ...

class Thin4x3Font(Font):
    height: int = ...
    data: Any = ...

class HalfBlock5x4Font(Font):
    height: int = ...
    data: Any = ...

class HalfBlock6x5Font(Font):
    height: int = ...
    data: Any = ...

class HalfBlockHeavy6x5Font(Font):
    height: int = ...
    data: Any = ...

class Thin6x6Font(Font):
    height: int = ...
    data: Any = ...

class HalfBlock7x7Font(Font):
    height: int = ...
    data: Any = ...
