from typing import Any, Optional
from urwid.display_common import BaseScreen

class HtmlGeneratorSimulationError(Exception): ...

class HtmlGenerator(BaseScreen):
    fragments: Any = ...
    sizes: Any = ...
    keys: Any = ...
    started: bool = ...
    colors: int = ...
    bright_is_bold: bool = ...
    has_underline: bool = ...
    def __init__(self) -> None: ...
    def set_terminal_properties(self, colors: Optional[Any] = ..., bright_is_bold: Optional[Any] = ..., has_underline: Optional[Any] = ...) -> None: ...
    def set_mouse_tracking(self, enable: bool = ...) -> None: ...
    def set_input_timeouts(self, *args: Any) -> None: ...
    def reset_default_terminal_palette(self, *args: Any) -> None: ...
    def draw_screen(self, size: Any, r: Any) -> None: ...
    def clear(self) -> None: ...
    def get_cols_rows(self): ...
    def get_input(self, raw_keys: bool = ...): ...

def html_span(s: Any, aspec: Any, cursor: int = ...): ...
def html_escape(text: Any): ...
def screenshot_init(sizes: Any, keys: Any) -> None: ...
def screenshot_collect(): ...
