from typing import Any

class MonitoredList(list):
    def set_modified_callback(self, callback: Any) -> None: ...
    __add__: Any = ...
    __delitem__: Any = ...
    __delslice__: Any = ...
    __iadd__: Any = ...
    __imul__: Any = ...
    __rmul__: Any = ...
    __setitem__: Any = ...
    __setslice__: Any = ...
    append: Any = ...
    extend: Any = ...
    insert: Any = ...
    pop: Any = ...
    remove: Any = ...
    reverse: Any = ...
    sort: Any = ...
    clear: Any = ...

class MonitoredFocusList(MonitoredList):
    def __init__(self, *argl: Any, **argd: Any) -> None: ...
    focus: Any = ...
    def set_focus_changed_callback(self, callback: Any) -> None: ...
    def set_validate_contents_modified(self, callback: Any) -> None: ...
    def __delitem__(self, y: Any): ...
    def __setitem__(self, i: Any, y: Any): ...
    def __delslice__(self, i: Any, j: Any): ...
    def __setslice__(self, i: Any, j: Any, y: Any): ...
    def __imul__(self, n: Any): ...
    def append(self, item: Any): ...
    def extend(self, items: Any): ...
    def insert(self, index: Any, item: Any): ...
    def pop(self, index: int = ...): ...
    def remove(self, value: Any): ...
    def reverse(self): ...
    def sort(self, **kwargs: Any): ...
    def clear(self): ...
