from typing import Any, Optional
from urwid import Edit

class NumEdit(Edit):
    ALLOWED: str = ...
    trimLeadingZeros: Any = ...
    def __init__(self, allowed: Any, caption: Any, default: Any, trimLeadingZeros: bool = ...) -> None: ...
    def valid_char(self, ch: Any): ...
    def keypress(self, size: Any, key: Any): ...

class IntegerEdit(NumEdit):
    base: Any = ...
    def __init__(self, caption: str = ..., default: Optional[Any] = ..., base: int = ...) -> None: ...
    def value(self): ...

class FloatEdit(NumEdit):
    significance: Any = ...
    def __init__(self, caption: str = ..., default: Optional[Any] = ..., preserveSignificance: bool = ..., decimalSeparator: str = ...) -> None: ...
    def value(self): ...
