from typing import Any

SAFE_ASCII_RE: Any
SAFE_ASCII_BYTES_RE: Any
widths: Any

def get_width(o: Any): ...
def decode_one(text: Any, pos: Any): ...
def decode_one_uni(text: Any, i: Any): ...
def decode_one_right(text: Any, pos: Any): ...
def set_byte_encoding(enc: Any) -> None: ...
def get_byte_encoding(): ...
def calc_text_pos(text: Any, start_offs: Any, end_offs: Any, pref_col: Any): ...
def calc_width(text: Any, start_offs: Any, end_offs: Any): ...
def is_wide_char(text: Any, offs: Any): ...
def move_prev_char(text: Any, start_offs: Any, end_offs: Any): ...
def move_next_char(text: Any, start_offs: Any, end_offs: Any): ...
def within_double_byte(text: Any, line_start: Any, pos: Any): ...
def process_east_asian_width() -> None: ...
