from typing import Any

class TextLayout:
    def supports_align_mode(self, align: Any): ...
    def supports_wrap_mode(self, wrap: Any): ...
    def layout(self, text: Any, width: Any, align: Any, wrap: Any) -> None: ...

class CanNotDisplayText(Exception): ...

class StandardTextLayout(TextLayout):
    def __init__(self) -> None: ...
    def supports_align_mode(self, align: Any): ...
    def supports_wrap_mode(self, wrap: Any): ...
    def layout(self, text: Any, width: Any, align: Any, wrap: Any): ...
    def pack(self, maxcol: Any, layout: Any): ...
    def align_layout(self, text: Any, width: Any, segs: Any, wrap: Any, align: Any): ...
    def calculate_text_segments(self, text: Any, width: Any, wrap: Any): ...

default_layout: Any

class LayoutSegment:
    text: Any = ...
    end: Any = ...
    def __init__(self, seg: Any) -> None: ...
    def subseg(self, text: Any, start: Any, end: Any): ...

def line_width(segs: Any): ...
def shift_line(segs: Any, amount: Any): ...
def trim_line(segs: Any, text: Any, start: Any, end: Any): ...
def calc_line_pos(text: Any, line_layout: Any, pref_col: Any): ...
def calc_pos(text: Any, layout: Any, pref_col: Any, row: Any): ...
def calc_coords(text: Any, layout: Any, pos: Any, clamp: int = ...): ...
