from pandas.tseries.offsets import DateOffset
from typing import Any, Optional

def get_period_alias(offset_str: str) -> Optional[str]: ...
def to_offset(freq: Any) -> Optional[DateOffset]: ...
def get_offset(name: str) -> DateOffset: ...
def infer_freq(index: Any, warn: bool=...) -> Optional[str]: ...

class _FrequencyInferer:
    index: Any = ...
    values: Any = ...
    warn: Any = ...
    is_monotonic: Any = ...
    def __init__(self, index: Any, warn: bool=...) -> None: ...
    def deltas(self): ...
    def deltas_asi8(self): ...
    def is_unique(self) -> bool: ...
    def is_unique_asi8(self): ...
    def get_freq(self) -> Optional[str]: ...
    def day_deltas(self): ...
    def hour_deltas(self): ...
    def fields(self): ...
    def rep_stamp(self): ...
    def month_position_check(self): ...
    def mdiffs(self): ...
    def ydiffs(self): ...

class _TimedeltaFrequencyInferer(_FrequencyInferer): ...
