DIRS = xeigtstc  xeigtstd  xeigtsts  xeigtstz  xlintstc  xlintstd  xlintstds \
       xlintstrfc  xlintstrfd  xlintstrfs  xlintstrfz  xlintsts  xlintstz \
       xlintstzc

LEVEL = ../..
COMPILER = gfortran

include $(LEVEL)/Makefile.common
