from typing import Any, Optional

def set_use_numexpr(v: bool = ...) -> None: ...
def set_numexpr_threads(n: Optional[Any] = ...) -> None: ...
def evaluate(op: Any, op_str: Any, a: Any, b: Any, use_numexpr: bool = ...): ...
def where(cond: Any, a: Any, b: Any, use_numexpr: bool = ...): ...
def set_test_mode(v: bool = ...) -> None: ...
def get_test_result(): ...
