from typing import Any

class MountEntry:
    dev: Any = ...
    point: Any = ...
    fstype: Any = ...
    options: Any = ...
    def __init__(self, dev: Any, point: Any, fstype: Any, options: Any) -> None: ...

MOUNT_PATTERN: Any

def mount_table(): ...
def mounted(fs: Any): ...
