from typing import Any

color_names: Any
color_html: Any
color_codes_simple: Any
attributes_ansi: Any
default_styles: Any

class FindNearest:
    r: Any = ...
    b: Any = ...
    g: Any = ...
    def __init__(self, r: Any, g: Any, b: Any) -> None: ...
    def only_basic(self): ...
    def all_slow(self, color_slice: Any = ...): ...
    def only_colorblock(self): ...
    def only_simple(self): ...
    def only_grey(self): ...
    def all_fast(self): ...

def from_html(color: Any): ...
def to_html(r: Any, g: Any, b: Any): ...
