from typing import Any, Optional

def hash_pandas_object(obj: Any, index: bool=..., encoding: str=..., hash_key: Optional[str]=..., categorize: bool=...) -> Any: ...
def hash_tuples(vals: Any, encoding: Any=..., hash_key: str=...) -> Any: ...
def hash_tuple(val: Any, encoding: str=..., hash_key: str=...) -> Any: ...
def hash_array(vals: Any, encoding: str=..., hash_key: str=..., categorize: bool=...) -> Any: ...
