from migrate.versioning.util.importpath import import_path as import_path
from migrate.versioning.util.keyedinstance import KeyedInstance as KeyedInstance
from sqlalchemy.pool import StaticPool as StaticPool
from typing import Any

log: Any

def load_model(dotted_name: Any): ...
def asbool(obj: Any): ...
def guess_obj_type(obj: Any): ...
def catch_known_errors(f: Any, *a: Any, **kw: Any): ...
def construct_engine(engine: Any, **opts: Any): ...
def with_engine(f: Any, *a: Any, **kw: Any): ...

class Memoize:
    fn: Any = ...
    memo: Any = ...
    def __init__(self, fn: Any) -> None: ...
    def __call__(self, *args: Any): ...
