from .. import cli
from typing import Any, Optional

class Image:
    size: Any = ...
    char_ratio: Any = ...
    def __init__(self, size: Optional[Any] = ..., char_ratio: float = ...) -> None: ...
    def best_aspect(self, orig: Any, term: Any): ...
    def show(self, filename: Any, double: bool = ...): ...
    def show_pil(self, im: Any) -> None: ...
    def show_pil_double(self, im: Any) -> None: ...

class ShowImageApp(cli.Application):
    double: Any = ...
    def colors_set(self, n: Any) -> None: ...
    size: Any = ...
    ratio: Any = ...
    def main(self, filename: Any) -> None: ...
