from .progress import Progress as Progress
from .termsize import get_terminal_size as get_terminal_size
from typing import Any, Optional

def readline(message: str = ...): ...
def ask(question: Any, default: Optional[Any] = ...): ...
def choose(question: Any, options: Any, default: Optional[Any] = ...): ...
def prompt(question: Any, type: Any = ..., default: Any = ..., validator: Any = ...): ...
def hexdump(data_or_stream: Any, bytes_per_line: int = ..., aggregate: bool = ...) -> None: ...
def pager(rows: Any, pagercmd: Optional[Any] = ...) -> None: ...
