from typing import Any, Optional

HAS_NUMPY: bool
getrefcount: Any
memo: Any
id_to_obj: Any
builtins_types: Any
dont_memo: Any

def get_attrs(obj: Any): ...
def get_seq(obj: Any, cache: Any = ...): ...
def memorise(obj: Any, force: bool = ...) -> None: ...
def release_gone() -> None: ...
def whats_changed(obj: Any, seen: Optional[Any] = ..., simple: bool = ..., first: bool = ...): ...
def has_changed(*args: Any, **kwds: Any): ...
__import__ = __import__
