import ctypes
from typing import Any

class _class: ...

class _class2:
    def __call__(self) -> None: ...

class _newclass: ...
class _newclass2: ...
class _Struct(ctypes.Structure): ...
odict = dict
registered: Any
failures: Any
succeeds: Any
