from ._dill import _locate_object as at, _proxy_helper as reference
from typing import Any

def parent(obj: Any, objtype: Any, ignore: Any = ...): ...
def parents(obj: Any, objtype: Any, depth: int = ..., ignore: Any = ...): ...
def children(obj: Any, objtype: Any, depth: int = ..., ignore: Any = ...): ...
refobject = at
