from typing import Any, Optional

def isfrommain(obj: Any): ...
def isdynamic(obj: Any): ...
def findsource(object: Any): ...
def getsourcelines(object: Any, lstrip: bool = ..., enclosing: bool = ...): ...
def getsource(object: Any, alias: str = ..., lstrip: bool = ..., enclosing: bool = ..., force: bool = ..., builtin: bool = ...): ...
def indent(code: Any, spaces: int = ...): ...
def outdent(code: Any, spaces: Optional[Any] = ..., all: bool = ...): ...
def dumpsource(object: Any, alias: str = ..., new: bool = ..., enclose: bool = ...): ...
def getname(obj: Any, force: bool = ..., fqn: bool = ...): ...
def getimport(obj: Any, alias: str = ..., verify: bool = ..., builtin: bool = ..., enclosing: bool = ...): ...
def importable(obj: Any, alias: str = ..., source: Optional[Any] = ..., builtin: bool = ...): ...
getblocks_from_history = getblocks

# Names in __all__ with no definition:
#   _importable
#   _namespace
#   _wrap
