# Extend the DIRS variable if you want make to setup new
# folders for you. This will create the missing directories
# and link the latex/Makefile.
#
DIRS = spidermonkey python sdcc tcc ruby
DIRS += 7z bzip2 gzip xz
DIRS += leveldb postgres sqlite3
DIRS += openssl ccrypt libmcrypt
DIRS += libav povray x264
DIRS += lammps linpack lulesh lulesh-omp lapack crafty
DIRS += crocopat minisat

LEVEL = ..

include $(LEVEL)/Makefile.common
