LEVEL=../..
DIRS= blowfish\
      bn\
      cast\
      des\
      dsa\
      ecdsa\
      hmac\
      md5\
      rc4\
      rsa\
      sha1\
      sha256\
      sha512\
      openssl\
      ssl

include $(LEVEL)/Makefile.common
