from ...connectors.pyodbc import PyODBCConnector
from .base import MySQLDialect, MySQLExecutionContext
from .types import TIME
from typing import Any

class _pyodbcTIME(TIME):
    def result_processor(self, dialect: Any, coltype: Any): ...

class MySQLExecutionContext_pyodbc(MySQLExecutionContext):
    def get_lastrowid(self): ...

class MySQLDialect_pyodbc(PyODBCConnector, MySQLDialect):
    colspecs: Any = ...
    supports_unicode_statements: bool = ...
    execution_ctx_cls: Any = ...
    pyodbc_driver_name: str = ...
    def __init__(self, **kw: Any) -> None: ...
dialect = MySQLDialect_pyodbc
