from typing import Any

class ReflectedState:
    columns: Any = ...
    table_options: Any = ...
    table_name: Any = ...
    keys: Any = ...
    fk_constraints: Any = ...
    ck_constraints: Any = ...
    def __init__(self) -> None: ...

class MySQLTableDefinitionParser:
    dialect: Any = ...
    preparer: Any = ...
    def __init__(self, dialect: Any, preparer: Any) -> None: ...
    def parse(self, show_create: Any, charset: Any): ...
