from ...connectors.zxJDBC import ZxJDBCConnector
from .base import BIT, MySQLDialect, MySQLExecutionContext
from typing import Any

class _ZxJDBCBit(BIT):
    def result_processor(self, dialect: Any, coltype: Any): ...

class MySQLExecutionContext_zxjdbc(MySQLExecutionContext):
    def get_lastrowid(self): ...

class MySQLDialect_zxjdbc(ZxJDBCConnector, MySQLDialect):
    jdbc_db_name: str = ...
    jdbc_driver_name: str = ...
    execution_ctx_cls: Any = ...
    colspecs: Any = ...
dialect = MySQLDialect_zxjdbc
