# Extend the DIRS variable if you want make to setup new
# folders for you. This will create the missing directories
# and link the latex/Makefile.
#
DIRS = 2mm 3mm atax bicg cholesky doitgen gemm gemver gesummv mvt \
       symm syr2k syrk trisolv trmm
LEVEL = ../../..

include $(LEVEL)/Makefile.common
