# Extend the DIRS variable if you want make to setup new
# folders for you. This will create the missing directories
# and link the latex/Makefile.
#
DIRS = datamining linear-algebra medley stencils

LEVEL = ..

include $(LEVEL)/Makefile.common
