from pandas.core.accessor import PandasDelegate
from typing import Any, Optional

class BaseAccessor:
    def __init__(self, data: Optional[Any] = ...) -> None: ...

class SparseAccessor(BaseAccessor, PandasDelegate):
    @classmethod
    def from_coo(cls, A: Any, dense_index: bool = ...): ...
    def to_coo(self, row_levels: Any = ..., column_levels: Any = ..., sort_labels: bool = ...): ...
    def to_dense(self): ...

class SparseFrameAccessor(BaseAccessor, PandasDelegate):
    @classmethod
    def from_spmatrix(cls, data: Any, index: Optional[Any] = ..., columns: Optional[Any] = ...): ...
    def to_dense(self): ...
    def to_coo(self): ...
    @property
    def density(self) -> float: ...
