from pandas._typing import Dtype as Dtype
from pandas.core.dtypes.base import ExtensionDtype
from typing import Any

class SparseDtype(ExtensionDtype):
    def __init__(self, dtype: Dtype=..., fill_value: Any=...) -> None: ...
    def __hash__(self) -> Any: ...
    def __eq__(self, other: Any) -> bool: ...
    @property
    def fill_value(self): ...
    @property
    def kind(self): ...
    @property
    def type(self): ...
    @property
    def subtype(self): ...
    @property
    def name(self): ...
    @classmethod
    def construct_array_type(cls): ...
    @classmethod
    def construct_from_string(cls, string: Any): ...
    @classmethod
    def is_dtype(cls, dtype: Any): ...
    def update_dtype(self, dtype: Any): ...
