name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements.txt
        pip install codecov
        pip install pytest-cov

    - name: Run integration tests
      run: |
        coverage run -p `which benchbuild` bootstrap -s
        pytest --cov-config=./.coveragerc --cov=./ benchbuild tests
        coverage run -p `which benchbuild` config view
        coverage run -p `which benchbuild` project view
        coverage run -p `which benchbuild` experiment view
        coverage run -p `which benchbuild` -vvvvv run --full test
        coverage combine -a
        coverage report

    - name: Upload coverage report
      run: codecov
