name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unittests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install system dependencies for CI
      run: |
        sudo apt-get install time unionfs-fuse libfuse-dev clang

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true

    - name: Install the project
      run: |
        uv sync --locked --all-extras --dev

    - name: Run unittests
      env:
        # Avoid 50 char hard-limit of podman. These are enforced because of
        # a kernel limit of 128-chars for socket paths.
        BB_CONTAINER_RUNROOT: "/tmp"
        BB_CONTAINER_ROOT: "/tmp"
      run: |
        git config --global protocol.file.allow always

        uv run pytest --cov-config=./.coveragerc --cov=benchbuild --ignore=tests/integration benchbuild tests
        uv run pytest --cov-config=./.coveragerc --cov=benchbuild tests/integration

    - uses: actions/upload-artifact@master
      with:
        name: coverage-unittests-${{ matrix.python-version }}
        path: ./.coverage


  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        db_support: [true, false]

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install system dependencies for CI
      run: |
        sudo apt-get install time unionfs-fuse libfuse-dev clang slurm-client

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true

    - name: Install the project
      run: |
        uv sync --locked --all-extras --dev

    - name: Run integration tests
      env:
        BB_DB_ENABLED: ${{ matrix.db_support }}
        BB_DB_CONNECT_STRING: "sqlite://"
        BB_COVERAGE_COLLECT: true
        BB_COVERAGE_PATH: ${{ github.workspace }}
        BB_COVERAGE_CONFIG: ${{ github.workspace }}/.coveragerc
        BB_CONTAINER_ROOT: ${{ runner.temp }}
        BB_CONTAINER_RUNROOT: ${{ runner.temp }}
        BB_VERBOSITY: 5
      run: |
        source .venv/bin/activate
        coverage run -p benchbuild bootstrap -s
        coverage run -p benchbuild config view
        coverage run -p benchbuild experiment view
        coverage run -p benchbuild project view
        coverage run -p benchbuild run --full test
        coverage run -p benchbuild slurm -E empty test
        coverage run -p benchbuild slurm -E raw bzip2/benchbuild -- container --runroot /foo/bar
        coverage run -p benchbuild run -E raw bzip2/benchbuild
        coverage run -p benchbuild container run -E raw bzip2/benchbuild
        coverage run -p benchbuild container bases --export -E raw bzip2/benchbuild
        coverage run -p benchbuild container bases --import -E raw bzip2/benchbuild
        coverage run -p benchbuild container rmi --with-projects -E raw bzip2/benchbuild
        coverage combine
        coverage report -m

    - uses: actions/upload-artifact@master
      with:
        name: coverage-integration-${{ matrix.python-version }}
        path: ./.coverage

  upload_coverage:
    needs: [unittests, integration]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12"]

    steps:
    - uses: actions/checkout@v5

    - uses: actions/download-artifact@master
      with:
        name: coverage-unittests-${{ matrix.python-version }}
        path: ./.coverage.unittests

    - uses: actions/download-artifact@master
      with:
        name: coverage-integration-${{ matrix.python-version }}
        path: ./.coverage.integration

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true

    - run: |
        ls -lah .
        uv sync --locked --all-extras --dev
        uv pip install coverage
        uv run coverage combine -a ./.coverage.integration/.coverage ./.coverage.unittests/.coverage
        uv run coverage xml

    - name: Upload coverage report
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml

  docs:
    needs: [unittests, integration]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true

    - name: Setup a git user
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Install the project
      run: |
        uv sync --locked --all-extras --group docs
