name: Unittests
on:
  workflow_call:
    inputs:
      python-version:
        description: "The python version to use"
        type: string
        required: false
        default: "3.14"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: ./.github/actions/setup-runner
        with:
          python-version: "${{ inputs.python-version }}"

      - name: Run unittests
        env:
          # Avoid 50 char hard-limit of podman. These are enforced because of
          # a kernel limit of 128-chars for socket paths.
          BB_CONTAINER_RUNROOT: "/tmp"
          BB_CONTAINER_ROOT: "/tmp"
        run: |
          git config --global protocol.file.allow always

          uv run pytest --cov-config=./.coveragerc --cov=benchbuild --ignore=tests/integration benchbuild tests
          uv run pytest --cov-config=./.coveragerc --cov=benchbuild tests/integration

          find . -type f -iname '*.coverage*'

      - uses: actions/upload-artifact@v7
        with:
          name: coverage-unittests-${{ inputs.python-version }}
          path: ./.coverage
          # Security: Careful with adding wildcard patterns above!
          include-hidden-files: true
