name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unittests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies for CI
      run: |
        sudo apt-get install time unionfs-fuse libfuse-dev clang

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements.txt
        pip install -r test-requirements.txt

    - name: Test bootstrapping
      run: |
        coverage run `which benchbuild` bootstrap -s

    - name: Run unittests
      run: |
        pytest --cov-append --cov-config=./.coveragerc --cov=benchbuild benchbuild tests
        coverage combine -a

    - uses: actions/upload-artifact@master
      with:
        name: coverage-data
        path: ./coverage


  integration:
    needs: unittests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies for CI
      run: |
        sudo apt-get install time unionfs-fuse libfuse-dev clang

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements.txt
        pip install -r test-requirements.txt

    - uses: actions/download-artifact@master
      with:
        name: coverage-data
        path: ./coverage

    - name: Run integration tests
      run: |
        coverage run -p `which benchbuild` config view
        coverage run -p `which benchbuild` project view
        coverage run -p `which benchbuild` experiment view
        coverage run -p `which benchbuild` -vvvvv run --full test
        coverage run -p `which benchbuild` -vvvvv slurm -E empty test
        coverage combine -a

    - uses: actions/upload-artifact@master
      with:
        name: coverage-data
        path: ./coverage

  upload_coverage:
    needs: [unittests, integration]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/download-artifact@master
      with:
        name: coverage-data
        path: ./coverage

    - run: |
        python -m pip install --upgrade pip
        pip install coverage
        coverage xml

    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml

  docs:
    needs: [unittests, integration]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements.txt
        pip install -r doc-requirements.txt

    - name: Build documentation
      run: |
        mkdocs build

    - name: Deploy documentation
      if: ${{ github.event_name == 'push' }}
      run: |
        mkdocs gh-deploy
