name: Unittests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  unittests:
    needs: prepare

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
    # - name: Check pre-commit
    #   uses: j178/prek-action@v2
    #   with:
    #     show-verbose-logs: false
      - uses: ./.github/actions/setup-runner
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Run unittests
        env:
          # Avoid 50 char hard-limit of podman. These are enforced because of
          # a kernel limit of 128-chars for socket paths.
          BB_CONTAINER_RUNROOT: "/tmp"
          BB_CONTAINER_ROOT: "/tmp"
        run: |
          git config --global protocol.file.allow always

          uv run pytest --cov-config=./.coveragerc --cov=benchbuild --ignore=tests/integration benchbuild tests
          uv run pytest --cov-config=./.coveragerc --cov=benchbuild tests/integration

      - uses: actions/upload-artifact@master
        with:
          name: coverage-unittests-${{ matrix.python-version }}
          path: ./.coverage
