name: Build Documentation
on:
  push:
    branches:
      - master
      - doc/deploy-docs-to-ghpages
jobs:
  doc:
    name: Deploy documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install system dependencies for CI
      run: |
        sudo apt-get install time unionfs-fuse libfuse-dev clang

    - name: Install BenchBuild
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install portray

    - name: Build documentation
      run: |
        ./docs/build.sh

    - name: Deply gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build
