name: Build Documentation
on: [push]
jobs:
  doc:
    name: Deploy documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies for CI
      run: |
        sudo apt-get install time unionfs-fuse libfuse-dev clang

    - name: Install BenchBuild
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install pdoc3

    - name: Build documentation
      run: |
        ./docs/build.sh

    - name: Deply gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build
