from migrate.versioning import pathed
from migrate.versioning.config import operations as operations
from typing import Any

log: Any

class BaseScript(pathed.Pathed):
    def __init__(self, path: Any) -> None: ...
    @classmethod
    def verify(cls, path: Any) -> None: ...
    def source(self): ...
    def run(self, engine: Any) -> None: ...
