from migrate.versioning.script import base
from typing import Any

class PythonScript(base.BaseScript):
    @classmethod
    def create(cls, path: Any, **opts: Any): ...
    @classmethod
    def make_update_script_for_model(cls, engine: Any, oldmodel: Any, model: Any, repository: Any, **opts: Any): ...
    @classmethod
    def verify_module(cls, path: Any): ...
    def preview_sql(self, url: Any, step: Any, **args: Any): ...
    def run(self, engine: Any, step: Any) -> None: ...
    @property
    def module(self): ...
